name: Color Workflow

on:
  push:
    branches:
      - main

jobs:
  set_color_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_WORKSPACE/GITHUB_OUTPUT"

  get_color_job:
    needs: set_color_job
    runs-on: ubuntu-latest
    steps:
      - name: Get color
        run: echo "The selected color is ${{ needs.set_color_job.outputs.SELECTED_COLOR }}"
