on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: url
        run: echo "GITHUB_OUTPUT=$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
          - run: echo "${{needs.job1.outputs.steps.url.outputs.test}}"

