on: push

jobs:
  
  job1:
    runs-on: ubuntu-latest
    outputs:
      myoutput: ${{ steps.step1.outputs.myoutput }}
    steps:
      - name: set output
        id: step1
        run: |
          text="hey"
          echo "myoutput=$text" >> $GITHUB_OUTPUT
          echo "deployed to $text"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: retrieve output
        run: |
          echo "${{ needs.job1.outputs.myoutput }}"
