on: push

jobs:
  
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: set output
        id: step1
        run: echo "myoutput=text" >> $GITHUB_OUTPUT

      - name: print output
        run: echo ${{ steps.step1.outputs.myoutput }}
